apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.2
    chart: ingress-nginx
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true